### ISSUE TITLE
Maven build

### ISSUE THREAD

**Issue by bengtmartensson** [aclemons/java-readline#2]
Today, a Maven build is almost a requirement for integration in the Java/free software ecosystem. 

I have a [Mavenized "fork"](https://github.com/bengtmartensson/java-readline), but I would like some feedback before I start working on a pull request.

**Comment by aclemons** [comment]
It might be nice for people hacking on java-readline or projects with a dependency on it.

But speaking with my package maintainer cap on, we must not make maven mandatory for building. Luckily, this project currently has no extra java dependencies, so it would be simple enough to support a maven build and an ant or simple javac based build simultaneously.

**Comment by aclemons** [comment]
I cherry-picked the changes from your repo and updated a couple of things. I have elected to not move all the files to match the maven conventions for now. That might be something for `1.0`.

**Comment by bengtmartensson** [comment]
Great. I do not think it is necessary to change the directory structure.
